###########mode (a+)
file = open ("demo123.txt",mode = "a+")
writeline=file.write("\nwelcome to python life harsha")
print(file.tell())
file.seek(0)
readline=file.read()
print(readline)
file.close()
############mode (r+)
file = open("demo123.txt",mode="r+")
write_data = file.write("thank you")
file.close()

file = open("demo123.txt",mode= "r+")
read_data = file.read()
print(read_data)
file.close()
